services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: vroomchat-php:8.4
    networks:
      - vroomchat
    volumes:
      - appdata:/var/www/html     # shared code + vendor lives inside Docker
    working_dir: /var/www/html
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    networks:
      - vroomchat
    ports:
      - "8080:80"          # <-- visit http://localhost:8080
    volumes:
      - appdata:/var/www/html     # read ONLY from shared volume
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    image: postgres:18
    container_name: vroomchat-postgres
    networks:
      - vroomchat
    restart: unless-stopped
    environment:
      POSTGRES_DATABASE: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql
    ports:
        - "5432:5432"

volumes:
  appdata:
  db_data:
    driver: local

networks:
  vroomchat:
    driver: bridge
