services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: vroomchat-php:8.4
    networks:
      - vroomchat
    working_dir: /app
    env_file:
        - .env
    ports:
      - "8001:8000"
    volumes:
      - .:/app:cached   # host code mounted for hot reload
    depends_on:
      - db

  db:
    image: postgres:18
    networks:
      - vroomchat
    restart: unless-stopped
    environment:
      POSTGRES_DATABASE: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql
    ports:
      - "5432:5432"

volumes:
  db_data:

networks:
  vroomchat:
    driver: bridge
